### PR TITLE
support for overriding maintenance mode during NR auth flow

### PR DESCRIPTION
**Pull request by cstryker**

### CODE REVIEW

**Review by CalvinAllen — APPROVED** [review]

**Comment by bcanzanella** [comment]
don't merge this!

**Comment by CalvinAllen** [comment]
@bcanzanella @cstryker Converted to draft so we don't accidently merge it.

**Comment by cstryker** [comment]
@CalvinAllen good plan, sorry i didn't make that more clear

**Comment by bcanzanella** [comment]
can this PR be closed @cstryker ?

**Comment by cstryker** [comment]
@bcanzanella yes, though it's a strange situation ... we might want to keep this branch "around" in case we need to do another "override maintenance mode" build in the future, but we also don't want to merge it ... and i fear if we just keep it without deleting it, it will get lost among all the other orphaned branches ... not sure what the best solution is

**Comment by bcanzanella** [comment]
@cstryker how about this: i'll put something in our wiki calling out this branch & its functionality. if needed in the future, we'll have it documented. sound ok?

**Comment by bcanzanella** [comment]
Search internal wiki for `Unified Identity debugging` (first result)

**Pull request closed without merging**
