### PR TITLE
Customized PR filters (WIP)

### PR DESCRIPTION
**Pull request by ppezaris**
**This PR Addresses:**  
[filter PRs only for the repos you have open](https://trello.com/c/hTiOo71k/4673-filter-prs-only-for-the-repos-you-have-open)

### CODE REVIEW

**Comment by ppezaris** [comment]
not ready for merge yet but feel free to have a look @brian&nbsp;

**Comment by ppezaris** [comment]
okay i'm at a point where i need some help from brian and colin...

**Comment by ppezaris** [comment]
Is this ready to be merged in?

**Comment by bcanzanella** [comment]
> 
> 
> Is this ready to be merged in?

ready on my end

**Pull request merged**
