### PR TITLE
NR-161545 Upgrade node.js to 18.15.0

### PR DESCRIPTION
**Pull request by dsellarsnr**

### CODE REVIEW

**Comment by bcanzanella** [comment]
@dsellarsnr check in Node.cs public static bool EnsureVersion() has a version check on node.

also, when this gets in, please ask all the devs to upgrade their node versions

**Comment by bcanzanella** [comment]
also, will TC need any changes for this?

**Comment by dsellarsnr** [comment]
Ah I didn't realize how the vs node worked. Looks like i can upgrade it from 16 to 18 in agent/package.json via pkg

**Comment by dsellarsnr** [comment]
TeamCity changes already done

**Pull request merged**
